---
- name: creating the epeal file in 
  hosts: all
  tasks: 
  - block:
    - name: install the epeal repository
      command: yum install epeal
      when: ansible_distribution_major_version == '7'
    rescue:
    - name: copy the epel file
      copy:
       src: /tmp/epel.repo 
       dest: /etc/yum.repos.d/
