---
- name: creating the anible facts
  hosts: all 
  tasks: 
  - name: creating the drectory
    command: mkdir -p /etc/ansible/facts.d/
  - name: creating the file
    file:
     path: /etc/ansible/facts.d/httpd.fact
     state: touch
     mode: 0644
  - name: adding the line
    lineinfile:
     path: /etc/ansible/facts.d/httpd.fact
     line: "{{ item }}"
     insertafter: EOF
    with_lines: cat local
...
